import Link from "next/link";

import Head from "next/head";
const about = () => {
  return (
    <div>
      <Head>
        <title>Weeeeeee | About </title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <h2>About page</h2>
      <p>
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nemo, vel,
        veniam assumenda odit dolores tempore voluptatem qui earum minus eius
        mollitia ratione repudiandae voluptas quidem sit a doloremque similique
        tenetur?
      </p>
    </div>
  );
};

export default about;
